### ISSUE TITLE
Tasin said to

### ISSUE THREAD

**Issue by IPmu** [Viren070/Emulator-Manager#14]
What viren thinks he looks like:
![images](https://github.com/Viren070/Emulator-Manager/assets/125932628/b468d4a6-8611-4adf-8baf-a85ed91dd84e)
what he actually looks like:
![AlbedoBase_XL_uncanny_indian_man_sitting_with_rubbish_around_h_3](https://github.com/Viren070/Emulator-Manager/assets/125932628/b368aa66-cd48-4212-9230-007c2abb11b4)

**Comment by Viren070** [comment]
Acc a jokeman

**Comment by IPmu** [comment]
> Acc a jokeman

AI generated "Boy named Viren rajeskumar being an average indian "

**Comment by Viren070** [comment]
![image](https://github.com/Viren070/Emulator-Manager/assets/71220264/455ed617-e1ce-433d-a3d6-7829bda6a37a)
this your uncle?
