### ISSUE TITLE
Virus Total scan detects malicious

### ISSUE THREAD

**Issue by DealsBeam** [Viren070/Emulator-Manager#15]
https://www.virustotal.com/gui/file/dc0399ec36881e4743567495df20b2ca829beb43901038dba6294a7fe9a68db8

**Comment by Viren070** [comment]
The file is not a virus. The detections are false positives. The code is open-source and if you do not believe me then you can [run the source code](https://www.amazon.co.uk/gp/product/B0CB5WCNN9/ref=ewc_pr_img_1?smid=A1AN08RHB7JYIU&psc=1). 

Also already answered in #12.
