### ISSUE TITLE
Can't download the title db file for yuzu and ryujinx

### ISSUE THREAD

**Issue by LaReunion974** [Viren070/Emulator-Manager#24]
**Describe the bug**
Can't download the title db for yuzu and ryujinx and gave an error

**To Reproduce**
1. launch the app
2. try to click on "manage rom" under the yuzu or ryujinx tab
3. start the download 
4. and nothing happen

**Expected behavior**
download and install the title db file

**Screenshots**

error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1962, in __call__
  File "customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "customtkinter\windows\widgets\ctk_button.py", line 194, in _draw
    self._canvas.delete("background_parts")
  File "tkinter\__init__.py", line 2894, in delete
_tkinter.TclError: invalid command name ".!yuzuframe.!ctkframe4.!yuzuromframe.!ctkframe.!switchromsframe.!progresswindow.!progressframe.!ctkbutton.!ctkcanvas"
Exception in thread Thread-129 (download_titles_db):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "gui\frames\switch_roms_frame.py", line 404, in download_titles_db
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Viren070** [comment]
I believe I have fixed the issue of the exception being raised. However, the exception was only raised because it either failed to completely download the file or failed to add the titleDB to cache. I will release a new version with this fix and let me know if the issue still occurs.

**Comment by LaReunion974** [comment]
No probleme i just found your amazing project and want to test it however i can do more investigation for bug testing and help you

**Comment by Viren070** [comment]
Thanks. If you do find any more bugs, please do report them by creating an issue and I will do my best to fix it.

**Comment by LaReunion974** [comment]
No probleme 👍

**Comment by LaReunion974** [comment]
hum why does he can't move the file ?
![image](https://github.com/Viren070/Emulator-Manager/assets/102532446/f0ed916e-aced-44a6-bbef-27f244fd001f)

**Comment by Viren070** [comment]
I'm not too sure about that, try deleting the cache folder and re-launching the app.

**Comment by Viren070** [comment]
I see that you have the app downloaded to another drive. You can create a file called PORTABLE.txt inside the other drive. This will use a folder within the other drive to store all the data. This could fix the issue.

**Comment by Viren070** [comment]
I found the cause of the issue you were facing. Since you are running Emulator Manager within the F drive, the titileDB is initally downloaded to the F drive. The app will attempt to move the file to the cache directory using os.rename. Since the cache directory is in another drive, os.rename fails to move the file. This can be fixed by using shutil.move instead. I will have to do this for each instance. 

For now, you can simply do as I said in my previous comment.
